/**
 * Z-Agent Shared Type Definitions
 *
 * This file contains all core type definitions used across the Z-Agent monorepo.
 * All types are documented with detailed comments to help with understanding.
 */

import { z } from "zod";

// =============================================================================
// Agent Core Types
// =============================================================================

/**
 * Represents a single message in the agent conversation
 */
export interface AgentMessage {
  /** Unique identifier for the message */
  id: string;
  /** Role of the message sender */
  role: "user" | "assistant" | "system";
  /** Content of the message */
  content: string;
  /** Timestamp when message was created */
  timestamp: Date;
  /** Optional tool calls made by the assistant */
  toolCalls?: ToolCall[];
}

/**
 * Represents a tool invocation (action taken by the agent)
 */
export interface ToolCall {
  /** Unique identifier for this tool call */
  id: string;
  /** Name of the tool being called */
  name: string;
  /** Arguments passed to the tool (JSON object) */
  arguments: Record<string, unknown>;
  /** Result returned by the tool (populated after execution) */
  result?: unknown;
  /** Error message if tool execution failed */
  error?: string;
}

/**
 * Risk level for a tool (determines if approval is needed)
 */
export enum ToolRiskLevel {
  /** Safe tools that don't modify state (e.g., read operations) */
  SAFE = "safe",
  /** Tools that modify data but are reversible (e.g., create files) */
  MODERATE = "moderate",
  /** Tools that make destructive changes (e.g., delete files) */
  DANGEROUS = "dangerous",
  /** Critical operations that could affect system stability */
  CRITICAL = "critical",
}

/**
 * Definition of a tool that the agent can use
 */
export interface Tool<TArgs = Record<string, unknown>> {
  /** Unique name for the tool */
  name: string;
  /** Human-readable description of what the tool does */
  description: string;
  /** Risk level of this tool (determines approval requirements) */
  riskLevel: ToolRiskLevel;
  /** Whether this tool requires user approval before execution */
  requireApproval: boolean;
  /** Zod schema for validating tool arguments */
  parameters: z.ZodSchema<TArgs>;
  /** Function that executes the tool logic */
  execute: (args: TArgs) => Promise<unknown>;
}

// =============================================================================
// Plan/Build Types
// =============================================================================

/**
 * Represents a file discovered during the Build phase code scanning
 */
export interface CodeFile {
  /** Path to the file (relative or absolute) */
  path: string;
  /** File extension (e.g., '.ts', '.tsx') */
  extension: string;
  /** Programming language detected */
  language: string;
  /** Number of lines in the file */
  lineCount: number;
  /** Imports found in the file (if analyzed) */
  imports?: string[];
  /** Exports found in the file (if analyzed) */
  exports?: string[];
}

/**
 * Represents a dependency between two files or modules
 */
export interface Dependency {
  /** Source file that has the dependency */
  from: string;
  /** Target file being imported/required */
  to: string;
  /** Type of import (e.g., 'import', 'require') */
  type: "import" | "require" | "dynamic";
}

/**
 * Result of the Build phase - contains analyzed code structure
 */
export interface BuildResult {
  /** All files discovered during scanning */
  files: CodeFile[];
  /** Dependency graph showing relationships between files */
  dependencies: Dependency[];
  /** Entry points identified (main files, routes, etc.) */
  entryPoints: string[];
  /** Summary statistics */
  stats: {
    totalFiles: number;
    totalLines: number;
    languages: Record<string, number>;
  };
}

/**
 * A single task to be executed by the Plan agent
 */
export interface Task {
  /** Unique identifier for the task */
  id: string;
  /** Human-readable description of what to do */
  description: string;
  /** Files this task will operate on */
  targetFiles: string[];
  /** Tools this task will use */
  requiredTools: string[];
  /** Current status of the task */
  status: "pending" | "in_progress" | "completed" | "failed" | "blocked";
  /** Tasks that must be completed before this one can start */
  dependencies: string[];
  /** Error message if task failed */
  error?: string;
  /** Result of task execution (if completed) */
  result?: unknown;
}

/**
 * Queue of tasks generated by Build phase to be executed by Plan phase
 */
export interface TaskQueue {
  /** Unique identifier for this task queue */
  id: string;
  /** User request that generated this queue */
  userRequest: string;
  /** Build result that informed the task generation */
  buildResult: BuildResult;
  /** All tasks in the queue (in order of execution) */
  tasks: Task[];
  /** Current position in the queue */
  currentIndex: number;
  /** Overall status of the queue */
  status: "pending" | "in_progress" | "completed" | "failed";
}

// =============================================================================
// Agent State Types
// =============================================================================

/**
 * Current state of the agent execution
 */
export type AgentState =
  /** Agent is thinking about what to do next */
  | "thinking"
  /** Agent is executing a tool */
  | "acting"
  /** Agent is observing the result of its action */
  | "observing"
  /** Agent is waiting for user approval */
  | "awaiting_approval"
  /** Agent has completed successfully */
  | "completed"
  /** Agent encountered an error */
  | "error";

/**
 * Runtime state of the agent during execution
 */
export interface AgentRuntime {
  /** Current state of the agent */
  state: AgentState;
  /** Message history */
  messages: AgentMessage[];
  /** Current task being executed (if in Plan mode) */
  currentTask?: Task;
  /** Task queue (if in Plan mode) */
  taskQueue?: TaskQueue;
  /** Tools waiting for approval */
  pendingApprovals: ToolCall[];
  /** Error information if in error state */
  error?: string;
}

// =============================================================================
// Configuration Types
// =============================================================================

/**
 * Configuration for agent execution
 */
export interface AgentConfig {
  /** Which AI model to use */
  model: "claude-3-5-sonnet-20241022" | "claude-3-5-haiku-20241022";
  /** API key for the AI provider */
  apiKey: string;
  /** Maximum number of iterations before giving up */
  maxIterations: number;
  /** Whether to enable Plan/Build mode */
  enablePlanBuild: boolean;
  /** Root directory for code scanning (in Build mode) */
  projectRoot: string;
  /** Tools available to the agent */
  tools: Tool[];
}

// =============================================================================
// MCP Types (Future)
// =============================================================================

/**
 * Configuration for connecting to an MCP server
 */
export interface MCPConfig {
  /** Unique name for this MCP connection */
  name: string;
  /** URL of the MCP server (if remote) */
  url?: string;
  /** Command to run for local MCP servers */
  command?: string;
  /** Arguments to pass to the MCP command */
  args?: string[];
  /** Environment variables for the MCP process */
  env?: Record<string, string>;
}

/**
 * Tool provided by an MCP server
 */
export interface MCPTool {
  /** Name of the MCP server providing this tool */
  serverName: string;
  /** Tool definition (same structure as regular Tool) */
  tool: Tool;
}
